version: '3'
services:

  web:
    build: .
    ports:
      - "5000:5000"
      - "443:443"
    environment:
      FLASK_ENV: development
      FLASK_APP: wsgi
      FLASK_DEBUG: 1
      APP_SETTINGS: config.DevelopmentConfig
      GOOGLE_CLIENT_ID: 452758247766-sisbc4uart9knl6jeihdn8rbgrjoadb5.apps.googleusercontent.com
      GOOGLE_CLIENT_SECRET: KV-V0fvNHh1-ncG9CuYFFSWz
      GOOGLE_DISCOVERY_URL: https://accounts.google.com/.well-known/openid-configuration
      RDS_PORT: 5432
      RDS_USERNAME: wtfdiw
      RDS_PASSWORD: Passw0rd!
      RDS_HOSTNAME: pg
      RDS_DB_NAME: wtfdiw_development
      MOVIE_API_BASE_URL: https://api.themoviedb.org/3
      MOVIE_API_KEY: 8adf3f49948fc809e928e509c90d99a1
    volumes:
      - .:/code
    depends_on:
      - pg

  pg:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: wtfdiw_development
      POSTGRES_USER: wtfdiw
      POSTGRES_PASSWORD: Passw0rd!
    ports:
      - '5432:5432'
    expose:
      - '5432'