"""empty message

Revision ID: 8240da7adfab
Revises: e3fa50d4ee07
Create Date: 2020-04-12 21:47:15.022829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8240da7adfab'
down_revision = 'e3fa50d4ee07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session',
    sa.Column('user_id', sa.Float(), nullable=False),
    sa.Column('token', sa.String(), nullable=True),
    sa.Column('expiration', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('session')
    # ### end Alembic commands ###
